#!/usr/bin/python
# -*- python -*-

"""
NAME
	%(program)s - Monitor and maintain an aggregate symlink directory.

SYNOPSIS
	%(program)s [OPTIONS]

DESCRIPTION

        %(program)s will first scan, and then continuously monitor a list of
        source directories, in order to keep a target directory updated with
        symlinks to the aggregated content of the source directories, in
        priority order.  By default it goes to the background as a daemon, but
        it can be made to run in the foreground.

        In order to do its work it uses the inotify interface of Linux kernel
        2.6.13 and later. It will not work if the inotify interface is absent.

        Example: Let's say that you have the source directory list:
        ["/foo/a/", "/bar/b/", "/baz/c/"]; and a target directory "/fum/t/".
        If the contents of the source directories are:

            /foo/a/
                xx
                xy
                xz
                
            /bar/b/
                xx
                yy
                zz

            /baz/c/
                xy
                yy
                yz

        then the target directory will be made to contain the following:

            /fum/t/
                xx -> /foo/a/xx
                xy -> /foo/a/xy
                xz -> /foo/a/xz
                yy -> /bar/b/yy
                yz -> /baz/c/yz
                zz -> /bar/b/zz

        Note that xx, which occurs in both /foo/a/ and /bar/b/, is linked to
        /foo/a/ because that occurs before /bar/b/ in the source list; and in
        the same manner, yy is linked to /bar/b/yy rather than /baz/c/yy
        because /bar/b/ occurs before /baz/c/ in the source list.

%(options)s

FILES
        %(program)s reads its configuration from the following files (if
        found), in the given order:
        
            <bin-dir>/%(program)s.conf
            /etc/%(program)s.conf
            /etc/%(program)s/%(program)s.conf
            ~/.%(program)src

        where <bin-dir> is the directory where %(program)s is installed.

AUTHOR
	Written by Henrik Levkowetz, <henrik@levkowetz.com>. Uses the
        daemonize module from Chad J. Schroeder, from the Python Cookbook at
        http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/278731.


COPYRIGHT
	Copyright 2011 Henrik Levkowetz. All rights reserved.

        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are
        met:

        * Redistributions of source code must retain the above copyright
          notice, this list of conditions and the following disclaimer.

        * Redistributions in binary form must reproduce the above copyright
          notice, this list of conditions and the following disclaimer in the
          documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
        "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
        LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
        A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
        HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
        SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
        LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
        DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
        THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
        (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import re
import sys
import os.path
import getopt
import config
import StringIO
import syslog

# ------------------------------------------------------------------------------
# Misc. metadata

version = "0.31"
program = os.path.basename(sys.argv[0])
progdir = os.path.dirname(sys.argv[0])
progpath= os.path.abspath(__file__)

# ------------------------------------------------------------------------------
# Set up logging

syslog.openlog(program, syslog.LOG_USER | syslog.LOG_PID)
log = syslog.syslog

# ------------------------------------------------------------------------------
# Read config file


merger = config.ConfigMerger(lambda x, y, z: "overwrite")

default_conf = """
dry_run:        False
batch:          False
foreground:     False
file_pattern:   None
debug:          False
verbose:        False
report:         False
mappings: {
    default: {
        ignore_hidden:  True
        file_pattern:   None
        action:  symlink
        sources:        []
        target:         None
    }
}
"""

default = config.Config(StringIO.StringIO(default_conf))
conf    = config.Config(StringIO.StringIO(default_conf))

for conffile in [progdir+"/"+program+".conf",
                "/etc/"+program+".conf",
                "/etc/"+program+"/"+program+".conf",
                os.path.expanduser("~/."+program+"rc"),
            ]:
    if os.path.exists(conffile):
        if conf.verbose:
            note("Reading configuration file '%s'" % os.path.abspath(conffile))
        else:
            log("Reading configuration file '%s'" % os.path.abspath(conffile))
        merger.merge(conf, config.Config(conffile))

# ------------------------------------------------------------------------------
# Create list of options, for the help text

options = ""
for line in re.findall("\n +(if|elif) +opt in \[(.+)\]:\s+#(.+)\n", open(sys.argv[0]).read()):
    if not options:
        options += "OPTIONS\n"
    options += "        %-16s %s\n" % (line[1].replace('"', ''), line[2])
options = options.strip()

# ------------------------------------------------------------------------------
# Process options

# with ' < 1:' on the next line, this is a no-op:
if len(sys.argv) < 1:
    print __doc__ % locals()
    sys.exit(1)

try:
    opts, args = getopt.gnu_getopt(sys.argv[1:], "bc:dfhinrvV", ["batch", "config:", "debug", "foreground", "ignore-hidden", "help", "report", "verbose", "version", ])
except Exception, e:
    print "%s: %s" % (program, e)
    sys.exit(1)

# process option switches
for opt, value in opts:
    if not opt:
        pass
    elif opt in ["-b", "--batch"]:      # Only run initial scan and update.  Implies -f
        conf.batch = True
        conf.foreground = True
    elif opt in ["-c", "--config"]:
        merger.merge(conf, config.Config(value))
    elif opt in ["-d", "--debug"]:      # Run with debug output
        conf.debug = True
        conf.verbose = True
    elif opt in ["-f", "--foreground"]: # Run in the foreground, don't daemonize
        conf.foreground = True
    elif opt in ["-i", "--ignore-hidden"]: # Ignore file names starting with '.'
        conf.ignore_hidden = True
    elif opt in ["-n", "--dry-run"]: # Don't do anything, just show what would be done
        conf.dry_run = True
    elif opt in ["-r", "--report"]: # Show existing links
        conf.report = True
        conf.batch  = True
        conf.foreground = True
    # stock switches
    elif   opt in ["-h", "--help"]:     # Output this help, then exit
        print __doc__ % globals()
        sys.exit(1)
    elif   opt in ["-v", "--verbose"]:     # Be more verbose
        conf.verbose = True
    elif opt in ["-V", "--version"]:    # Output version, then exit
        print program, version
        sys.exit(0)

# ----------------------------------------------------------------------
# If we've come this far we weren't invoked just for help or version info, so
# log the start.

log("%(program)s v%(version)s starting (%(progpath)s)" % globals())

# ----------------------------------------------------------------------
def say(s):
    log(s)
    sys.stdout.write("%s\n" % (s))

# ----------------------------------------------------------------------
def note(s):
    log(s)
    if conf.verbose and conf.foreground:
        sys.stdout.write("%s\n" % (s))

# ----------------------------------------------------------------------
def info(s):
    if conf.debug:
        note(s)
        
# ----------------------------------------------------------------------
def err(s, error=1):
    log("Error: %s" % s)
    sys.stderr.write("%s: Error: %s\n\n" % (program, s))

# ----------------------------------------------------------------------
def die(s, error=1):
    err(s)
    log("Terminating")
    sys.exit(error)

# ------------------------------------------------------------------------------
# Utility functions

# def mkdir(path):
#     if not path.exists():
#         print "Creating directory '%s'" % path
#         path.mkdir()
#         return True
#     return False
# 
# def mkfile(file):
#     path = file.dirname()
#     path.mkdir()
#     if not file.exists():
#         file.touch()
#         return True
#     return False

import pwd
import grp
import daemonize
from path import path as Path
import pyinotify as inotify
from pyinotify import WatchManager, Notifier, EventsCodes as EventCodes, ProcessEvent as EventHandler
import subprocess
import shlex

# ------------------------------------------------------------------------------


def follow(link, conf):
    """Return the file that the link corresponds to.
    If link is a symlink, this is rather trivial; we use readlink() and
    abspath() if necessary.  If this is a hard link, we need to compare
    the inode of the link with the inode of each of the possible sources,
    and return the right one.
    """
    if link.islink():
        #note("   link is symlink to %s" % link.readlinkabs())
        return link.readlinkabs()
    else:
        inode = link.stat().st_ino
        base  = link.basename()
        for dir in conf.dirs:
            file = dir / base
            if file.exists() and file.stat().st_ino == inode:
                #note("   link is hard link to %s" % file)
                return file
        #note("   link source not found")
        return link

def symlink(file, link, conf):
    if file.exists() and not file.isdir():
        if link.lexists():
            old = link.readlinkabs()
            opath = old.parent
            fpath = file.parent
            # to avoid exceptions if one of these aren't in the source list,
            # place what we're looking for as a sentinel at the end of the
            # list:
            if (conf.dirs+[fpath]).index(fpath) < (conf.dirs+[opath]).index(opath) or not link.exists() or not link.islink():
                note("replacing     %s -> %s" % (link, old))
                if not conf.dry_run:
                    link.unlink()
                note("new symlink   %s -> %s" % (link, file))
                if not conf.dry_run:
                    file.symlink(link)
            else:
                # note("won't symlink; lower priority: %s << %s" % (opath, fpath))
                pass
        else:
            note("creating symlink %s -> %s" % (link, file))
            if not conf.dry_run:
                try:
                    file.symlink(link)
                except OSError, e:
                    err("%s when trying to symlink %s -> %s as %s" % (e, link, file, pwd.getpwuid(os.getuid())[0]))
    else:
        note("won't link; file doesn't exist: %s" % file)


def hardlink(file, link, conf):
    #
    def resolve_hardlink(link, conf):
        inode = link.stat().st_ino
        base  = link.basename()
        for dir in conf.dirs:
            file = dir / base
            if file.exists() and file.stat().st_ino == inode:
                #note("   link is hard link to %s" % file)
                return file
        #note("   link source not found")
        return link

    if file.exists() and not file.isdir():
        if link.lexists():
            old = resolve_hardlink(link, conf)
            opath = old.parent
            fpath = file.parent
            # to avoid exceptions if one of these aren't in the source list,
            # place what we're looking for as a sentinel at the end of the
            # list:
            if (conf.dirs+[fpath]).index(fpath) < (conf.dirs+[opath]).index(opath) or not link.exists() or link.islink():
                note("replacing     %s -> %s" % (link, old))
                if not conf.dry_run:
                    link.unlink()
                note("new hard link %s == %s" % (link, file))
                if not conf.dry_run:
                    file.link(link)
            else:
                # note("won't link; lower priority: %s << %s" % (opath, fpath))
                pass
        else:
            note("creating hard link %s == %s" % (link, file))
            if not conf.dry_run:
                try:
                    file.link(link)
                except OSError, e:
                    err("%s when trying to hard link %s == %s as %s" % (e, link, file, pwd.getpwuid(os.getuid())[0]))
    else:
        note("won't link; file doesn't exist: %s" % file)


def unlink(file, link, conf):
    if not conf.action in batch_actions:
        return
    try:
        old = link.readlinkabs()
    except OSError: # the file is gone
        old = None
    if old == file or old == None:
        note("unlinking %s -> %s" % (link, file))
        if not conf.dry_run:
            try:
                link.unlink()
            except OSError, e:
                err(e)
        # if we have the same file in another directory with lesser
        # precedence than the one we just removed, we need to link that one
        # in: 
        if old:
            for dir in conf.dirs:
                file = dir/old.name
                if file.exists():
                    if conf.ignore_hidden and file.name.startswith('.'):
                        note ("ignoring hidden file %s" % file)
                    else:
                        conf.action(file, link, conf)
    else:
        note("won't unlink: symlink didn't match: target was %s but %s -> %s" % (file, link, old))

def rsync(src, tgt, conf):
    try:
        if conf.foreground:
            pin, pout, perr = sys.stdin, sys.stdout, sys.stderr
        else:
            pin, pout, perr = None, log, log
        subprocess.call(conf.params + [src, tgt], stdin=pin, stdout=pout, stderr=perr)
    except OSError as e:
        err("%s when trying to rsync %s -> %s as %s" % (e, link, file, pwd.getpwuid(os.getuid())[0]))

def skip(src, tgt, conf):
    return


# ------------------------------------------------------------------------------

class EventHandler(EventHandler):
    def __init__(self, pevent=None, **kwargs):
        self.conf = kwargs["conf"]
        return super(EventHandler, self).__init__(pevent, **kwargs)
    def process_IN_CREATE(self, event):
        info( "Saw creation: %s" % event)
        file = Path(event.pathname)
        link = self.conf.target / event.name
        self.conf.create(file, link, self.conf)
    def process_IN_DELETE(self, event):
        info( "Saw deletion: %s" % event)
        file = Path(event.pathname)
        link = self.conf.target / event.name
        self.conf.delete(file, link, self.conf)
    def process_IN_MOVED_TO(self, event):
        info( "Saw move to: %s" % event)
        file = Path(event.pathname)
        link = self.conf.target / event.name
        self.conf.moveto(file, link, self.conf)
    def process_IN_MOVED_FROM(self, event):
        info( "Saw move from: %s" % event)
        file = Path(event.pathname)
        link = self.conf.target / event.name
        self.conf.movefrom(file, link, self.conf)
    def process_IN_CLOSE_WRITE(self, event):
        info( "Saw modification: %s" % event)
        file = Path(event.pathname)
        link = self.conf.target / event.name
        self.conf.modify(file, link, self.conf)


# ------------------------------------------------------------------------------

actions = {
    # action list:  (create, delete, move_to, move_from, modify):
    "symlink":      (symlink,  unlink, symlink,  unlink, skip),
    "hardlink":     (hardlink, unlink, hardlink, unlink, skip),
    "rsync":        (rsync,    skip,   rsync,    skip,   rsync),
}

batch_actions  = [
    symlink,
    hardlink,
]


note("Configuration:")
for name in conf:
    value = getattr(conf, name)
    if name == "mappings":
        for mname in conf.mappings:
            section = conf.mappings[mname]
            params = shlex.split(section.action)
            action = params[0]
            for dname in default.mappings.default:
                if not dname in section:
                    section[dname] = default.mappings.default[dname]
            for n in section:
                v = getattr(section, n)
                note("  %-20s: %-36s (%s)" % ("%s.%s"%(mname, n), v, type(v)))
            if action in actions:
                note("  ** section.action: %s" % action)
                section.create, section.delete, section.moveto, section.movefrom, section.modify = actions[action]
                section.params = params
            else:
                die("Unrecognized action in configuration: '%s'.  Possible actions are: %s" % (section.action, ", ".join(actions.keys())))
    else:
        # Set this value for all mappings which doesn't have it set
        for mname in conf.mappings:
            section = conf.mappings[mname]
            if not hasattr(section, name):
                setattr(section, name, value)
        note("  %-14s: %-42s (%s)" % (name, value, type(value)))

# ------------------------------------------------------------------------------
# Some assertions
#if not Path(conf.targetdir).exists():
#    die("The directory '%s' where symlinks should be placed doesn't exist." % conf.targetdir)
#assert(type(conf.masourcedirs) in [ list, config.Sequence ])

# ------------------------------------------------------------------------------
# Maybe daemonize

# Get user and group we should execute as
user, pw, uid, gid, gecos, home, shell = list(pwd.getpwnam(conf.daemon_user))
if "daemon_group" in conf:
    group, gpw, gid, members = list(grp.getgrnam(conf.daemon_group))

if not conf.foreground:
    note("Daemonizing...")
    pidfname = "/var/run/%s.pid" % program

    pidfile = open(pidfname, "w")
    os.chown(pidfile.name, uid, gid)
    pidfile.close()

    os.setgid(gid)
    os.setuid(uid)
    daemonize.createDaemon()

    pidfile = open(pidfname, "w")
    pidfile.write("%s" % os.getpid())
    pidfile.close()

    # Connect stdout and stderr to syslog, to catch messages, exceptions, traceback
    log("Redirecting stdout and stderr to syslog")
    syslog.write = syslog.syslog
    sys.stdout = syslog
    sys.stderr = syslog
else:
    note("Not daemonizing.")

# ----------------------------------------------------------------------
# Do the actual work

mask =  ( inotify.IN_CREATE |
          inotify.IN_DELETE |
          inotify.IN_MOVED_FROM |
          inotify.IN_MOVED_TO |
          inotify.IN_CLOSE_WRITE
        )

sections = []
for name in conf.mappings:
    section = conf.mappings[name]
    note("Section %s:" % name)
    section.target = Path(section.target)
    section.cwd = Path.getcwd()
    note("Making paths absolute")
    note(section.target)
    if not section.target.isabs() and not ':' in section.target:
        section.target = section.cwd / section.target
    note(section.target)
    if not section.target.exists():
        note("   creating target directory: %s" % section.target)
        section.target.makedirs(mode=0o755)
    else:
        note("   target directory: %s" % section.target)
    section.files = {}
    section.dirs = []
    note("   reading contents of source directories:")
    for dir in section.sources:
        dir = Path(dir.rstrip('/'))
        if dir.islink():
            note("     source directory %s is a symlink, using %s instead" % (dir, dir.readlinkabs()))
            dir = dir.readlinkabs()
        if not dir.isabs():
            dir = section.cwd / dir
        if not dir in section.dirs:
            section.dirs.append(dir)
            note("   - %s" % dir)
            section.files[dir] =  dir.listdir(section.file_pattern)
        else:
            note("   - skipping %s, it's already in the source list" % dir)
    if conf.report:
        if not conf.verbose:
            sys.stdout.write("\nSection %s: %s:\n" % (name, section.target))
        for file in section.target.listdir():
            if file.islink():
                sys.stdout.write("   %s -> %s\n" % (file, follow(file, section)))
            else:
                sys.stdout.write("   %s == %s\n" % (file, follow(file, section)))
        continue

    if not conf.batch:
        note("   setting up watchers and event handlers to monitor source directories")
        section.handler = EventHandler(conf=section)
        section.watchmgr = WatchManager()
        for dir in section.dirs:
            section.watchmgr.add_watch(dir, mask=mask)
        section.notifier = Notifier(section.watchmgr, section.handler)
        sections.append(section)

    note("   inspecting directories and updating links as needed")
    for dir in section.dirs:
        if section.action in batch_actions:
            note("   - %s: %s files" % (dir, len(section.files[dir])))
            for path in section.files[dir]:
                name = path.name
                src = dir / name
                tgt = section.target / name
                section.action(src, tgt, section)


if conf.batch:
    sys.exit(0)
   
note("Monitoring source directories for changes")
while 1:
    try:
        for section in sections:
            if section.notifier.check_events(timeout=100):
                section.notifier.read_events()
            section.notifier.process_events()

    except KeyboardInterrupt:
        # Stop monitoring if sigint is caught (Control-C).
        log('Pyinotify stops monitoring.')
        break

# Close internals
for section in sections:
    section.handler.stop()

